from __future__ import annotations

from .models import CandidateResult, WorkloadSpec


CPP_TYPES = {
    "uint64": "std::uint64_t",
    "uint64_t": "std::uint64_t",
    "uint32": "std::uint32_t",
    "uint32_t": "std::uint32_t",
    "int": "std::int64_t",
    "integer": "std::int64_t",
    "float": "double",
    "double": "double",
    "string": "std::string",
    "str": "std::string",
    "text": "std::string",
    "bool": "bool",
}


def _cpp_type(raw: str) -> str:
    return CPP_TYPES.get(raw.lower(), "std::string")


def generate_cpp_preview(spec: WorkloadSpec, candidate: CandidateResult) -> str:
    fields = "\n".join(f"    {_cpp_type(field.type)} {field.name};" for field in spec.fields)
    mapping = "\n".join(
        f"// query[{assignment.query_index}] {assignment.query_kind.value}"
        f"{f' on {assignment.field}' if assignment.field else ''} -> {assignment.primitive}"
        for assignment in candidate.assignments
    )

    primitive_comments = "\n".join(f"//   - {name}" for name in candidate.unique_primitives)
    return f'''// Generated by MORPHEUS MVP — PREVIEW ONLY
// Evidence state: PREDICTED_NOT_MEASURED
// Workload: {spec.name}
// Candidate: {candidate.id}
// A later verification phase must compile and differential-test generated artifacts.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace morpheus_generated {{

struct Record {{
{fields}
}};

// Selected physical primitives:
{primitive_comments}

// Routing plan:
{mapping}

class GeneratedIndex {{
public:
    void insert(const Record& record);
    void erase(const Record& record);
    void update(const Record& before, const Record& after);

    // Query-specific methods are emitted by the full P3 code generator.
    // This preview deliberately avoids pretending that unverified generated code is complete.

    [[nodiscard]] const char* candidate_id() const noexcept {{ return "{candidate.id}"; }}
}};

}} // namespace morpheus_generated
'''
